#
name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  extract-release-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extraction.outputs.tag }}
    steps:
      - id: extraction
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo "tag=${GITHUB_REF##*/}" >> ${GITHUB_OUTPUT}
  build-and-push-image:
    needs: extract-release-tag
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ needs.extract-release-tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
